### ISSUE TITLE
Fix 400 error on uploads page

### ISSUE THREAD

**Issue by bmatern** [IHIW/IHIW_Management#106]
Martin Maiers and Eric saw this in production and staging environemnts. I think the problem is in the uploadRepositroy.findByCreatedIn(colleages) method when we call getAllUploads()

Not a problem for my user, but I think project leaders are the problem.

**Comment by bmatern** [comment]
400 when changing file,
uploading a file without selecting a file from the desktop.

**Comment by cyt-mn** [comment]
Cannot be reproduced at the moment. Probably fixed by other changes in that area...

Open again, if that error reoccurs.
