### ISSUE TITLE
Upload of >1Mb files cause HTTP 500

### ISSUE THREAD

**Issue by cyt-mn** [IHIW/IHIW_Management#108]
"io.undertow.server.handlers.form.MultiPartParserDefinition$FileTooLargeException: UT000054: The maximum size 1048576 for an individual file in a multipart request was exceeded"

Check within that ticket if we can adjust the limit or whether we need to approach the upload differently.

**Comment by cyt-mn** [comment]
https://stackoverflow.com/questions/46805927/spring-multipart-file-upload-with-gridfs-size-limit-exception

**Comment by bmatern** [comment]
The 10MB upper limit is working as intended, perhaps in the future this limit would be adjusted. I can upload a 7MB file, but upload fails with 500 error for a 26MB file.

**Comment by bmatern** [comment]
Users are attempting to upload a 26 MB HML File (There are 96 samples in a single HML File, that's valid and we should handle this, Probably related to issue #189 ) , and getting a 500 error. 

To Fix:

Short Term:
- Raise limit to 100MB
Longer Term:
- Detect the error and tell user something better than "error.500"

**Comment by bmatern** [comment]
Also add notification for large uplaods? issue #186

**Comment by bmatern** [comment]
We need to look closer at this one.

In testing I tried to upload a 100MB file, and Still received 500 Error.

But the crash is a different kind, it is a java.lang.OutOfMemory error:

...
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: Java heap space

I suggest: Try to run the whole website, giving java more memory

**Comment by bmatern** [comment]
Yes, changing the start script to 

java -Xmx512m -jar 

resolved this issue.
