### ISSUE TITLE
Update the graphical field for Validation Status

### ISSUE THREAD

**Issue by bmatern** [IHIW/IHIW_Management#109]
Instead of true false, it should show (1/3) or (4/4)

**Comment by cyt-mn** [comment]
![image](https://user-images.githubusercontent.com/8983165/84766874-cff22500-afd1-11ea-84f5-29c8bc31cd45.png)

On mouseover, the validator and its feedback are shown...
![image](https://user-images.githubusercontent.com/8983165/84766906-e26c5e80-afd1-11ea-9052-9c7815ce0283.png)

**Comment by bmatern** [comment]
I think "Validation feedback" should also be displayed for the valid files, instead of just the "valid" text.

Because "Successfully converted to .haml" is good feedback
