### ISSUE TITLE
Uploads not shown for non-ADMIN users

### ISSUE THREAD

**Issue by cyt-mn** [IHIW/IHIW_Management#110]

**Comment by cyt-mn** [comment]
This was due to a merge conflict of the sorting of uploads. Fixed on develop.

**Comment by bmatern** [comment]
Uploads are visible for users, there is still some discussion on who SHOULD be able to see files.

Currently a PI cannot see another lab's uploads for the same project. Questionable if this is desirable but I think it works as intended.

**Comment by bmatern** [comment]
Lab members CAN see other labmembers' files, regardless of project.

lab members cannot see another lab's files.
