### ISSUE TITLE
Personal Data processing consent - required on new user and password reset interface (GDPR)

### ISSUE THREAD

**Issue by bmatern** [IHIW/IHIW_Management#114]
Email to existing users? No reply = no consent = delete user
Privacy Policy needs to be available

**Comment by bmatern** [comment]
2 issues
user and
ethical use of data (approve every upload, need checkbox)
   - Maybe the data matrices need to have approval? Not a big amount of work. But, the real data is in HML files.
   - Could be when the lab/project is created..
   - Extra button when subscribing. Already has one confirmation, could add the permission to this screen. Need a checkbox, not just a button that assumes.
   -  email to existing users... already need to email them.
         -with instructions on how to do that on the edit project screen
   -Upload page checks if there is consent? Otherwise error message. ( I think for testing users will be annoyed but whatever)

**Comment by bmatern** [comment]
Create or edit a Project
Each PI can set the IRB approval for their own lab on the edit project screen.

**Comment by Cornelieke-IHIW18** [comment]
I'm splitting this issue into two separate issues: one on processing Personal Data of the Workshop Participants (GDPR) and one on Project Data Sharing consent.

**Comment by Cornelieke-IHIW18** [comment]
Part of Privacy Statement: How we protect your (personal) data:
- using AWS as cloud provider ensures robust and resilient infrastructure and latest security technology
- all data transfers are encrypted (via https)
- access to the application respectively the data is restricted via username & password
- password data is hashed
- data access if further restricted by roles and permissions
