### ISSUE TITLE
Unsubscribe from Project button not visible even for subscribed projects

### ISSUE THREAD

**Issue by cyt-mn** [IHIW/IHIW_Management#116]

**Comment by Cornelieke-IHIW18** [comment]
The unsubscribe option is visible. I'll move this issue to approved.

**Comment by Cornelieke-IHIW18** [comment]
The button is visible, but as a LabMember I'm not authorized to unsubscribe. In this case, I should not be able to see the button. I'll move this to in Development again.

**Comment by cyt-mn** [comment]
could not reproduce. checked with @Cornelieke-IHIW18, so we move that to donw.
