### ISSUE TITLE
Remove double emailadresses/account

### ISSUE THREAD

**Issue by espierin** [IHIW/IHIW_Management#12]

**Comment by espierin** [comment]
Cornelieke will create an account. Eric will set the role.

**Comment by Cornelieke-GenDx** [comment]
Dependency: First issue #15 must be fixed

**Comment by espierin** [comment]
#15

**Comment by Cornelieke-GenDx** [comment]
Removed 9 users on production. Made a back-up file of all users in Excel first, so we can add them again if needed.
