### ISSUE TITLE
Edit Upload function needs updating. 

### ISSUE THREAD

**Issue by bmatern** [IHIW/IHIW_Management#121]
The save button causes a 400 error so the save should be rewritten

**Comment by bmatern** [comment]
If you try to edit the upload, and choose a new file, there is a 400 error.

I think the new file should replace the existing file on S3. Rename it to match the old file.

Use case:
1. Upload data matrix.  It is invalid, user must fix the errors.
2. Fix the errors in the data matrix validation report.
3. Edit the original upload on the website, and choose the corrected data matrix to replace the invalid one 
4. Was the problem fixed? Re-validate everything.

This new file should re-trigger conversions and validations. 
Test cases:
-Update the .csv file for a .haml file. Does it re-convert and re-validate both files?
-Data Matrix - Should re-validate the data matrix and re-create the validation report xlsx.
-HML file - did it repeat and overwrite the schema validation, and other (nmdp / miring) validation?

**Comment by bmatern** [comment]
#141 allows us to reselect files and alter the upload.

The upload database entry is fixed, before posting the new file. This means that, the SNS messaging does trigger, so the re-validations should still happen. Need to deploy to staging to check it 100%

Still missing: I can't seem to set the default value for the project. The project value is overwritten when the "edit upload" screen, and it is necessary to re-choose the project.

**Comment by bmatern** [comment]
I think previous issues have all been addressed, and re-uploading does indeed trigger validations and such, only one outstanding problem when changing the project of an upload

To recreate
Edit upload -> Choose a different Project -> Save.
400 error

**Comment by bmatern** [comment]
Choosing a project is not the problem, it was a problem with not choosing a new file.

Make the edit upload page load the previous file.  More information about the existing file.

**Comment by bmatern** [comment]
-Disable save until upload for new files. (Currently it ONLY enables save based on choosing the project?)
-Populate filename with the existing uploads

**Comment by cyt-mn** [comment]
> Make the edit upload page load the previous file. More information about the existing file.

@bmatern please create a new ticket for that.

**Comment by cyt-mn** [comment]
> -Disable save until upload for new files. (Currently it ONLY enables save based on choosing the project?)

fixed by #130

**Comment by bmatern** [comment]
When a new .CSV file is selected it will be revalidated. 

Changed the HAML converter so it deletes the (HAML) children of the CSV file. Then it repeats the conversion and validations.

In short, the HAML converter currently works with the new/edit upload logic.

**Comment by Cornelieke-IHIW18** [comment]
I tested editing a HAML file. Works fine, revalidates.
I replaced a HAML file with an HML file, and a HAML with an Antibody CSV file, both work fine too
