### ISSUE TITLE
Grouping projects per component:

### ISSUE THREAD

**Issue by espierin** [IHIW/IHIW_Management#13]
To make navigation easier for people, grouping per component is needed. We have three components.

**Comment by espierin** [comment]
https://www.ihiw18.org/ for projects and three components

Antigenicity&Immunogenicity
Immunogenetics
Bioinformatics

Use flags for marking the projects.

**Comment by Cornelieke-GenDx** [comment]
@inemp The name of the components are in Erics comment above

**Comment by Cornelieke-GenDx** [comment]
I successfully changed the component on two projects (382 and 389) on https://staging.ihiws.org/project, so for me, this is working.

**Comment by espierin** [comment]
Approved.

**Comment by espierin** [comment]
Only approve - not yet closed...
