### ISSUE TITLE
Deleting a parent upload fails when the parent has children.

### ISSUE THREAD

**Issue by bmatern** [IHIW/IHIW_Management#133]
Deleting the parent upload can delete from S3, but can't delete the Upload entry, because of the foreign key. I think this method should delete the children before deleting the parent.

Matthias:  Should be easiest to create a deleteByParentUpload in the repo. Then you call that once and then delete the parent.

**Comment by bmatern** [comment]
Latest version of feature/128 should fix this.

delete upload rest endpoint  loops to delete the children (both on S3 and their uploads), and proceeds to delete the parent afterwards.

**Comment by Cornelieke-IHIW18** [comment]
Works, I'm moving this issue to approved.
