### ISSUE TITLE
Admin UI for adding/removing labs to/from projects

### ISSUE THREAD

**Issue by cyt-mn** [IHIW/IHIW_Management#14]
Right now, there is a multi-select box for selecting participating labs for a project. This should be a bit more safe by manually adding/removing (without the multi-select box).

**Comment by Cornelieke-GenDx** [comment]
Added one lab to project 384, added two labs to 398 and later removed one of them from the project. This works. I just do not know if any emails were sent.

**Comment by espierin** [comment]
I received an email, but the content is rather uninformative and at some point incorrect.

> Dear nldspi

> There is a new lab that wants to register to your IHIW lab. Please login and manage your project's subscriptions.

> https://staging.ihiws.org
> Best regards 
> ihiwManagement Team.

It would help if it reports something like: 
-> There is a new ``<u>`user</u>` that wants to register to your IHIW lab. Please login and manage your project's subscriptions.

Ultimately, it would report the username/name.
