### ISSUE TITLE
Users cannot be deleted

### ISSUE THREAD

**Issue by espierin** [IHIW/IHIW_Management#15]
When logged in as administrator, users cannot be deleted.
![Screenshot from 2019-11-12 10-29-13](https://user-images.githubusercontent.com/51205347/68659406-83c09d00-0537-11ea-8a77-ed589c0662e3.png)

**Comment by espierin** [comment]
Pim will check for user(s) that could not be deleted. @PimVermeeren

**Comment by Cornelieke-GenDx** [comment]
I successfully deleted a couple of users, BUT we did not succeed in deleting user # 589. This one gives an error. Maybe this is something concerning just this user @cyt-mn ?
![image](https://user-images.githubusercontent.com/57407809/70517428-dee6af00-1b38-11ea-8064-99a32368645e.png)

**Comment by espierin** [comment]
It may have to do with the user roles. Could it be that users with certain roles cannot be deleted?

**Comment by espierin** [comment]
Btw: for users that cannot be deleted, it also fails when you press the "view" or "edit" button.

**Comment by Cornelieke-GenDx** [comment]
Yes, I saw the same thing # 591 cannot be deleted, viewed or edited either, but others with the role of labmember can.

**Comment by cyt-mn** [comment]
Good catch. This was actually an issue affecting (migrated) users with a whitespace in their login names. I fixed it by replacing login handles with underscores.

**Comment by espierin** [comment]
I checked the new version with user 589 and I could delete it. This one is now approved. I will move it to the next stage.

**Comment by espierin** [comment]
for #591:
before: 
![image](https://user-images.githubusercontent.com/51205347/70918539-7a878c00-201f-11ea-99aa-4a14c49c5cb3.png)
after:
![image](https://user-images.githubusercontent.com/51205347/70918596-9b4fe180-201f-11ea-8ed7-a159341b7ab0.png)
