### ISSUE TITLE
Add "Re-Validate" button for uploads

### ISSUE THREAD

**Issue by bmatern** [IHIW/IHIW_Management#150]
Validation is currently triggered when a new file is uploaded. An option to re-validate an upload would be great. 

Example use case:
-A data matrix is invalid because it is missing a supporting file
-Supporting file (HML?) is uploaded)
-Data matrix is still invalid, the only way to re-validate is by re-uploading the file.

**Comment by bmatern** [comment]
Not sure how to trigger this. 

A button?

Automatic on a timer? Invalid data matrices are re-validated on a schedule?

Revalidate data  matrices when an HML is uploaded?

**Comment by bmatern** [comment]
Some libraries can use small amount of java code to send signal to lambda function.

That's probably the easiest way.

Send a "refresh?" message to S3?  "Touch" command changes file? 

"Copy" file source and target are the same. Will that work? Just changes the meta information... S3 trigger may need to modify to listen to copy events.

**Comment by cyt-as** [comment]
aws s3 cp s3://path/to/file s3://path/to/file --metadata-directive REPLACE

**Comment by bmatern** [comment]
The command as suggested by Andreas does indeed seem to work.
 
I can run 
"aws s3 cp s3://bucket-name/filename.hml --region eu-central-1 s3://bucket-name/filename.hml --metadata-directive REPLACE"

And it did update the metadata. Since this is a copy command, Matthias changed the SNS trigger to listen to copy events, which allows the lambda functions to see the copy updates.

Conclusion: Running this copy event can indeed trigger re-validation. The next steps are to write a function so the website can do this, and make a button to trigger it.

**Comment by bmatern** [comment]
https://github.com/aws/aws-sdk-java/issues/1283

Suggests that we can create a  CopyObjectRequest using the Java SDK

**Comment by bmatern** [comment]
I suggest:

1. Add a [Revalidate] button on the View Upload page.
2. When this button is pressed, it will either Copy or Put the file back in the s3 bucket.
3. Hopefully that will trigger the step functions to re-validate this file. (Check if it worked on AWS - Step Functions)

Note:  "Copy" like in Andreas' example above could indeed trigger SNS/lambda functions, but the Step function/EventBridge triggers are different; they are triggered by the creation of a new (not copy) S3 object. It might be necessary to "Put" the file on top of the existing file on S3, instead of just copying the file.

https://docs.aws.amazon.com/step-functions/latest/dg/tutorial-cloudwatch-events-s3.html#tutorial-cloudwatch-events-s3-eb-notification

**Comment by bmatern** [comment]
Summary of our discussion on this today:

Ioannis is creating a method "repeatValidation()" in the script "upload-detail.component.ts." which is triggered by the [Re-validate] button. Great.

I think the logic of the repeatValidation() method can be similar to the "save()" method in "upload-update.component.ts".  But instead of this.createFromForm() you can use the upload that has already been loaded.

**Comment by bmatern** [comment]
"put" into the bucket (ihiw-management-upload-staging) is the important thing. If you have successfully "put" the file, you should see that the step function (staging-validation) was triggered

![image](https://user-images.githubusercontent.com/14239618/159898144-16c31125-4f3f-4995-8fc7-1e36f19fc871.png)
