### ISSUE TITLE
Unable to link user to lab: not all users visible in ihiw user edit screen.

### ISSUE THREAD

**Issue by PimVermeeren** [IHIW/IHIW_Management#17]
![image](https://user-images.githubusercontent.com/54659550/69138220-8c2c5100-0abe-11ea-9985-c96cd84f7750.png)

**Comment by FPR-GenDx** [comment]
In the ihiw_user controller the fuction that returns all users is a 'pagable', and it only returns page 1 of 20. So you only see 1/20th of all users.
This is a bug, and should be fixed otherwise linking users to labs is not possible.

**Comment by Cornelieke-GenDx** [comment]
The paging in the user dropdown is gone, so now you see and choose all existing users. I tested this by creating a new user via https://staging.ihiws.org/admin/user-management, because if a user registers him/herself, they already exist as an IHIW user with a lab code. 
So: tested and apporved
