### ISSUE TITLE
New User registration email fails

### ISSUE THREAD

**Issue by Cornelieke-GenDx** [IHIW/IHIW_Management#18]
https://staging.ihiws.org/register
https://data.ihiws.org/register

Registration works, but the feedback is not right, there is no confirmation page, you stay on the registration page and are tempted to click on "Register" again and again. Also, you do not get a confirmation email.

**Comment by Cornelieke-GenDx** [comment]
The confirmation email is not there anymore and the confirmation page does not appear either

**Comment by FPR-GenDx** [comment]
Work-a-round for this is to let the user register, and then immidiatly request a password reset. This will then send an email.

When registring a new user is created, but no email is sent. My guess is that is what is going wrong, email fails, so the app reports registration has failed.

**Comment by cyt-as** [comment]
If a new user registers the following scenarios are implemented:
- new user for existing lab > activation email is sent to lab PI
- new user with new lab > activation email is sent to email defined via activation-email property (admin@pirche.com on STAGING; spierings@ihiw18.org on PROD)

**Comment by Cornelieke-GenDx** [comment]
Tested and it looks like it works as it should. 
I'm a bit unsure because I do not know exactly what it should work like. I received an activation email for one user/email address and a reset password email for another. All users I myself registered for with different email addresses.
admin@pirsche.com received an activation email for a new user with a new lab, so that's good

Let's leave this as approved for now, in order to move forward.
