### ISSUE TITLE
Join project process

### ISSUE THREAD

**Issue by espierin** [IHIW/IHIW_Management#2]
Please implement the process for joining a project. This process should be as follows:

1) A PI selects the project he/she wants to join and submits a request
2) The request is being sent to the project leader including also the lab code
3) The project leader approves or rejects the request
4) The lab of the PI is added to the project
5) The PI receives a notification of the result

(It would be great if admin/chairs could add labs to projects easily via the lab page. For this, the lab list below should be created with check boxes. <- this will be fixed by #14 )

![Screenshot from 2019-11-12 09-38-48](https://user-images.githubusercontent.com/51205347/68655464-5d4b3380-0530-11ea-8114-966042940ad0.png)

**Comment by cyt-mn** [comment]
Within this ticket:
1. PIs should be able to send participations requests
2. Project leaders should see participation requests / reply them.
3. Notifications about state changes should be send out.

**Comment by cyt-mn** [comment]
ES: "Everybody should be able to see what projects are out. Details (participants and dat) are restricted to project leaders and admin/chairs. PIs should see only their own data within a project."

**Comment by cyt-mn** [comment]
A PI has subscribe buttons for all projects:
![image](https://user-images.githubusercontent.com/8983165/70893633-c0c2f800-1feb-11ea-8aa7-7af218c16f9c.png)

Pressing subscribe will give a dialog to confirm subscribing, email will be sent to all project leaders:
![image](https://user-images.githubusercontent.com/8983165/70893672-d9cba900-1feb-11ea-9af3-7329da965329.png)

Pending subscription will be shown as "waiting". Subscribe button disappears:
![image](https://user-images.githubusercontent.com/8983165/70893740-f831a480-1feb-11ea-89c0-ddf63545e6a2.png)

Project lists for Project Leaders (and Admin) shows pending subscriptions:
![image](https://user-images.githubusercontent.com/8983165/70899247-890d7d80-1ff6-11ea-8794-8e05472ca3a6.png)

Edit view of Project Leaders allows granting requests, press save to confirm:
![image](https://user-images.githubusercontent.com/8983165/70899340-b9edb280-1ff6-11ea-98d0-3f082b8df93d.png)

After subscription is confirmed, PI sees "Susbscribed" status and can unsubscribe:
![image](https://user-images.githubusercontent.com/8983165/70899507-0802b600-1ff7-11ea-852c-60bf60b00bdc.png)

Unsubscribe needs to be confirmed by dialog (unsubscribed projects can be requested again):
![image](https://user-images.githubusercontent.com/8983165/70899526-151fa500-1ff7-11ea-9bd8-f4df9977951e.png)

Project Leaders will see unsubscribed labs:
![image](https://user-images.githubusercontent.com/8983165/70899591-397b8180-1ff7-11ea-9209-fa3fc788ad03.png)

Admin can grant subscription, manually add labs and remove the relationship between lab and project completely (:
![image](https://user-images.githubusercontent.com/8983165/70899714-7b0c2c80-1ff7-11ea-8dcf-ecca46714fd0.png)

**Comment by espierin** [comment]
approved as per screenshots
