### ISSUE TITLE
Server Crashes Sometimes

### ISSUE THREAD

**Issue by bmatern** [IHIW/IHIW_Management#207]

**Comment by bmatern** [comment]
What we're trying this week:

Operating System Updates.

1) Stop Server Instance
2) Create a Server Image (because we are careful people)
3) Start Server Instance
4) Updates (using sudo yum update)
5) Start webserver (./start.sh)

**Comment by bmatern** [comment]
Updates applied on Staging and Prod. Lets give it two weeks, if we're seeing a crash, then we can try to use a different instance type.

Currently it's running on a t2.micro but maybe a different instance type is better.

Other ideas:
1) Can the server be rebooted and restarted when AWS detects that something went wrong?
2) Set up some kind of redundancy, load balancing or so (this gets complicated)

**Comment by bmatern** [comment]
Prod server has been working well, something went wrong yesterday. Seems to be different though. 

I still see the ALARM Healthcheck email, but AWS shows no issues with the health check, and I could already SSH to the machine. I had to start the webserver and it's ok. Maybe someone already rebooted it?

**Comment by bmatern** [comment]
Maybe this was something different, the webserver software crashed, rather than infrastructure

**Comment by bmatern** [comment]
One more crash today. EC2 instance was unresponsive, I had to Stop/Start the instance, then start the webserver. We should increase the instance type to see if it's a resource issue.

**Comment by cyt-as** [comment]
I've upgraded to the next higher tier of instance type (t2.micro >> t3.small). Double the compute units and double the main memory. Let's see if anything changes.
