### ISSUE TITLE
ihiw user user and lab combox should be autocompleted

### ISSUE THREAD

**Issue by ghost** [IHIW/IHIW_Management#25]
The list of users and labs will be large, and scrolling trough a list is not user friendly at all. I think it should not be too hard make it an autocomplete, I found an article where there are steps to make it work.
https://antoniogoncalves.org/2018/11/08/jhipster-angular-primeng-and-autocomplete/

**Comment by espierin** [comment]
@FPR-GenDx and @cyt-mn If the auto-completion takes more time it would already be VERY helpful if the drop-down menu for lab codes could be sorted alphabetically (as was done for countries). Adding labs to projects (as admin) is currently really a challenge.

**Comment by Cornelieke-GenDx** [comment]
Ioannis and I just looked at this issue, because we were checking what needed to be done, but it turns out that the dropdowns already have autocompletion. So let's discuss next week if we still need to improve this.
We tested in Chrome and Firefox btw.

**Comment by Cornelieke-GenDx** [comment]
From my perspective this works fine, so as far as I'm concerned we could close this issue.
