### ISSUE TITLE
More than one project leader per project

### ISSUE THREAD

**Issue by espierin** [IHIW/IHIW_Management#3]
Please implement the option to add more than one project leader to a single project.

**Comment by espierin** [comment]
Second half of december.

**Comment by Cornelieke-GenDx** [comment]
Tested and it works. Finding the right project leader is not that easy, because the dropdown list is unorganised and you can only type one letter to "search" in the list. We will create a new issue for this.

**Comment by Cornelieke-GenDx** [comment]
Question: should the list show only users that have the ProjectLeader role? Because that is not the case at the moment, it looks like all users can be added to projects.

**Comment by espierin** [comment]
@Cornelieke-GenDx will test this.

**Comment by Cornelieke-GenDx** [comment]
Tested and approved.
