### ISSUE TITLE
Send email to user if account was activated by PI or IHIW admin

### ISSUE THREAD

**Issue by cyt-as** [IHIW/IHIW_Management#33]
If a user registers an activation email is sent to the lab PI (existing lab) or the IHIW admin (new lab). If the account is then activated by them the user is not notified about that via email.

**Comment by Cornelieke-GenDx** [comment]
A newly registered user does now receive an activation email. 
Maybe we should look at the text. At the moment it says:
Dear [first name]

Your ihiwManagement account was activated.

Best regards
The IHIW Team

This could be something like:
Dear [first name],

Thank you for registering. Your account was activated. Please go to https://data.ihiws.org/ to login.
If you have any questions about the IHIW database, visit [url]. For more information about the18th International HLA & Immunogenetics Workshop, got to www.ihiw18.org.

Best regards,
The IHIW Team
_Names?_

**Comment by Cornelieke-GenDx** [comment]
I created #56 for the text and will put this one in Approved
