### ISSUE TITLE
User manual for database usage (workshop participants perspective).

### ISSUE THREAD

**Issue by espierin** [IHIW/IHIW_Management#41]

**Comment by espierin** [comment]
Focus first on PI (project leader) roles and the participants roles (lab member). How to get an account and labcode, join a lab, join a project, approve joining a project. Content first, format and location later.

**Comment by bmatern** [comment]
A description of how the project subscriptions works. What will the user see?
Do we have something on this already?

**Comment by Cornelieke-IHIW18** [comment]
@bmatern On subscribing to a project we have this page: https://www.ihiw18.org/docs/ihiws-database-user-documentation/projects/join-a-project/

**Comment by bmatern** [comment]
Instructions for data matrices: Users should name files based on unique identifiers for the patient (donor and recipient). 

We can suggest a naming scheme like 
'Patient_32.hml'
'Patient_32.csv' or 'Patient_32.haml'

In the data matrix, listing Patient_32.hml should find one unique upload.
