### ISSUE TITLE
Add xml validation based on schema

### ISSUE THREAD

**Issue by espierin** [IHIW/IHIW_Management#51]

**Comment by inemp** [comment]
Could you have a look at this? If it is any helpful? I compiled it and it does an ok job.https://github.com/nmdp-bioinformatics/miring-validator (validator for hml files).

**Comment by cyt-mn** [comment]
This could also be implemented as an AWS Lambda job... So python could again be a valid, streamlined option.

**Comment by bmatern** [comment]
Schema validation for HML is working great, still fixes needed for HAML files. This might work automatically when we create the new upload object for the converted haml files.

**Comment by bmatern** [comment]
Next step - create lambda functions for production.
