### ISSUE TITLE
Test and validate the online converter

### ISSUE THREAD

**Issue by espierin** [IHIW/IHIW_Management#53]
Use output files form vendors' software and convert. Check the haml manually. Document the validation.

**Comment by bmatern** [comment]
Some HAML Schema violations for the converted HAML file. 
Necessary to fix these before approving.

**Comment by bmatern** [comment]
Schema is compliant on converted files.

Data is mapped according to this spreadsheet:

https://github.com/IHIW/Converters/blob/master/HAMLConverterPy/HAML%20Converter%20Data%20Mapping.xlsx
