### ISSUE TITLE
The "view project" and "edit project" page gives an error (404)

### ISSUE THREAD

**Issue by Cornelieke-GenDx** [IHIW/IHIW_Management#55]
For some roles (LabMember, ProjectLeader, ProjectAffiliate). So as a project leader, you cannot edit your own project.
Page: https://staging.ihiws.org/project 
Error page: https://staging.ihiws.org/404

**Comment by cyt-mn** [comment]
- PI -> can 'view' project (works), cannot 'edit' project (works)
- LabMember -> can 'view' project (broken), cannot 'edit' project (works)

**Comment by Cornelieke-GenDx** [comment]
Tested and it works. My project leader test-account can now view and edit their projects.
