### ISSUE TITLE
New text for the notification email a newly activated user receives after their account has been activated

### ISSUE THREAD

**Issue by Cornelieke-GenDx** [IHIW/IHIW_Management#56]
Related to #33
Text proposal (note: we do not yet have a url to refer to the FAQ or equivalent):

Dear [first name],

Thank you for registering. Your account was activated. Please go to https://data.ihiws.org/ to login.
If you have any questions about the IHIW database, visit [url]. For more information about the18th International HLA & Immunogenetics Workshop, got to www.ihiw18.org.

Best regards,
The IHIW Team

**Comment by Cornelieke-GenDx** [comment]
Pushed to developer branch

**Comment by Cornelieke-GenDx** [comment]
The email text was changed and an activated user receives this new text. 
Before we go live we have to adjust the text again though, because of a few small mistakes and the fact that we didn't have the right link to the user documentation yet.

**Comment by espierin** [comment]
https://www.ihiw18.org/docs/ihiws-database-user-documentation/

**Comment by espierin** [comment]
Best regards,
 
Eric Spierings and Sebastiaan Heidt
 
Co-chairs of 18th IHIWS

**Comment by inemp** [comment]
Updated it. Pushed to develop branch

**Comment by Cornelieke-GenDx** [comment]
Yes, it is correct.
I received this email:

Dear Cornelieke,

Thank you for registering. Your account was activated. Please go to https://data.ihiws.org/ to login.If you have any questions about the IHIW database, visit https://www.ihiw18.org/docs/ihiws-database-user-documentation/. For more information about the18th International HLA & Immunogenetics Workshop, got to www.ihiw18.org.

Best regards,
_Eric Spierings and Sebastiaan Heidt Co-chairs of 18th IHIWS_

**Comment by Cornelieke-GenDx** [comment]
The only thing wrong is: the urls/links are not clickable. @inemp will look into this.
