### ISSUE TITLE
Add lab to project as admin does not work in Chrome

### ISSUE THREAD

**Issue by Cornelieke-GenDx** [IHIW/IHIW_Management#60]
N.B. ON PRODUCTION
For instance: https://staging.ihiws.org/project/382/edit

The add lab option does not work. 
Labs can only subscribe themselves, but as admin we want to be able to add labs to projects too.

**Comment by cyt-mn** [comment]
In Firefox this is working - in Chrome, clicking the dropdown doesn't add the item.

**Comment by Cornelieke-GenDx** [comment]
In MS Edge it works (tested on staging, not the latest, Chromium based version of Edge, but version 44.18362.449.0. 
I tested deleting an upload, add and remove a lab from a project, add and remove a project leader from a project, editing a project

**Comment by Cornelieke-GenDx** [comment]
In Chrome I can now successfully add or remove a lab to a project, but I **cannot** add a project leader to a project. Almost there I guess ;)

**Comment by Cornelieke-GenDx** [comment]
Adding project leaders in Chrome works now too.
