### ISSUE TITLE
Including the data matrix for the antigenicity & immunogenicity projects

### ISSUE THREAD

**Issue by espierin** [IHIW/IHIW_Management#67]

**Comment by bmatern** [comment]
In progress:
1. Validator for uploaded xlsx files (Do referenced files exist by HML ID or by filename. Exactly one file) Metadata is correct. Consider - do the Referenced files need to be valid? could set multiple types of validations

2) Improve excel spreadsheet with limited options for input.

**Comment by bmatern** [comment]
Mostly working, some things to remember: 

1) Hml Filename 
        Validate against these options:
	HML ID (Almost)
	GL String (Almost)

- Only compare against uploads from the same project and lab. Currently I'm validating against any upload, this could invalidate files if other labs use the same IDs.

- Probably, I should allow searching for a specific file type as well. Searching for a .HML file should not invalidate against the existenc of a .haml file

- Add configuration values for the project IDs. Validators check based on the project ID but it's currently hardcoded. They're different in every environment. Somehow check if the config value exists and print error messages if it is missing.
