### ISSUE TITLE
Make visible who is connected to a lab

### ISSUE THREAD

**Issue by Cornelieke-IHIW18** [IHIW/IHIW_Management#69]
As an admin, or as a PI or project leader, there is no easy way to see who is connected to a lab or see all the lab members. It would be very handy to have a way of knowing this. This includes contact details like an email address. I've had this wish myself, but also Tami and Kazu are asking about this feature.

**Comment by Cornelieke-GenDx** [comment]
_First sketch_
**Show lab members on the lab page**
 - after navigating to "Entities > Laboratory > View xxx lab" or 
 - after clicking on the name of a lab that subscribed to a (your) project

**When viewing a lab page**
a. Add a label (Principal Investigator?) above the details of the one registering that lab
b. Add section showing all lab members
c. The names of the lab members should be a link to their user page (standard user page or IHIW User page?)

**The view user page** 
d. Shows their name, their email address, the lab (code or name) they are connected to (= link to the lab page) and their role (PI or Lab Member, maybe Project Leader too, if applicable) 

**The edit user page**
Add editable fields for name, email address, lab (code or name), role

**Think about/Questions**
_Rights_: 
Who can see a lab page and who can see the lab members?
Who can edit the new items on a lab page?
Who can edit the new user page or changed IHIW user page?

How about the registration page? Preferably no option to add lab members there, so no change?

_When editing a lab page_
Add users as lab members? Or not?
Remove lab members? Or not? 

The view user page could be the existing "View IHIW user" page with adjustments
The edit user page could be the existing "Edit IHIW user" page with adjustments

**To do**
Change the view lab page (a. b. c.)
Change the edit lab page?
Create a view user page or change the view IHIW user page (d.)
Create an edit user page or change the edit IHIW user page (e.)

![ViewLabPage](https://user-images.githubusercontent.com/57407809/77072226-a71bbd00-69ed-11ea-9649-bd47e25a4e7c.png)
![ViewIHIWuserPage](https://user-images.githubusercontent.com/57407809/77072224-a6832680-69ed-11ea-9077-45494c1774a8.png)

**Comment by cyt-mn** [comment]
Scope of the ticket:
- Adjust the "View lab" page:
  - hide unnecessary fields (toggle fold)
  - add table for lab members (id, name, email, role) below the lab code (also link to user)

Edit lab page remains unchanged (for the moment)

**Comment by cyt-mn** [comment]
Admins can see all users of all labs.
Project leaders can see all users of the labs that are connected to a project where they are project leader of.
PIs can see PIs of all labs.
Lab members can see all users only of their own lab.
