### ISSUE TITLE
Writing the haml converter

### ISSUE THREAD

**Issue by espierin** [IHIW/IHIW_Management#8]
Writing a converter that will run on the server and convert raw data files from onelambda and immucor to haml format

**Comment by espierin** [comment]
Gijs uploaded the converter. zip file has been created including description. Some items still unclear (see description). Test files have been included.

**Comment by cyt-mn** [comment]
Add download buttons for converted files to the File Upload view.

**Comment by cyt-mn** [comment]
The latest version from @gijswams is now on AWS Lambda both for staging and prod. So converting files can be tested.

Note: Currently there is no validation happening. Therefore the application also does not adjust the "valid" flag accordingly.

**Comment by espierin** [comment]
@bmatern plesae check with Talitha and/or Walter to get some OneLambda files for testing.

**Comment by bmatern** [comment]
HAML converter is working, Ben needs to draw a map of how the data is being handled and where it goes.

**Comment by bmatern** [comment]
Data is mapped according to this spreadsheet:

https://github.com/IHIW/Converters/blob/master/HAMLConverterPy/HAML%20Converter%20Data%20Mapping.xlsx
